[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dp_wizard"
authors = [{name = "The OpenDP Project", email = "info@opendp.org"}]
readme = "README-PYPI.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
keywords = ["differential privacy"]
dynamic = ["version", "description"]
dependencies = ["faicons", "ipykernel", "jupyter-client", "jupytext", "matplotlib", "nbconvert", "opendp[polars]==0.13.0", "pyyaml", "shiny"]

[options]
python_requires = ">=3.10"

[project.scripts]
# Prefer dash in name where allowed (repo named and executable)
# but provide alias to minimize frustration.
dp-wizard = "dp_wizard:main"
dp_wizard = "dp_wizard:main"

[project.urls]
Home = "https://github.com/opendp/dp-wizard"

[tool.pyright]
include = ["dp_wizard"]
ignore = ["**/no-tests/"]

[project.optional-dependencies]
app = ["anyio==4.9.0", "appdirs==1.4.4", "appnope==0.1.4", "asgiref==3.8.1", "asttokens==3.0.0", "attrs==25.3.0", "beautifulsoup4==4.13.4", "bleach[css]==6.2.0", "click==8.1.8", "comm==0.2.2", "contourpy==1.3.2", "cycler==0.12.1", "debugpy==1.8.14", "decorator==5.2.1", "defusedxml==0.7.1", "deprecated==1.2.18", "exceptiongroup==1.2.2", "executing==2.2.0", "faicons==0.2.2", "fastjsonschema==2.21.1", "fonttools==4.57.0", "h11==0.14.0", "htmltools==0.6.0", "idna==3.10", "ipykernel==6.29.5", "ipython==8.35.0", "jedi==0.19.2", "jinja2==3.1.6", "joblib==1.4.2", "jsonschema-specifications==2024.10.1", "jsonschema==4.23.0", "jupyter-client==8.6.3", "jupyter-core==5.7.2", "jupyterlab-pygments==0.3.0", "jupytext==1.17.0", "kiwisolver==1.4.8", "linkify-it-py==2.0.3", "markdown-it-py==3.0.0", "markupsafe==3.0.2", "matplotlib-inline==0.1.7", "matplotlib==3.10.1", "mdit-py-plugins==0.4.2", "mdurl==0.1.2", "mistune==3.1.3", "narwhals==1.35.0", "nbclient==0.10.2", "nbconvert==7.16.6", "nbformat==5.10.4", "nest-asyncio==1.6.0", "numpy==2.2.4", "opendp[polars]==0.13.0", "orjson==3.10.16", "packaging==24.2", "pandocfilters==1.5.1", "parso==0.8.4", "pexpect==4.9.0", "pillow==11.2.1", "platformdirs==4.3.7", "polars==1.12.0", "prompt-toolkit==3.0.51", "psutil==7.0.0", "ptyprocess==0.7.0", "pure-eval==0.2.3", "pyarrow==19.0.1", "pygments==2.19.1", "pyparsing==3.2.3", "python-dateutil==2.9.0.post0", "python-multipart==0.0.20", "pyyaml==6.0.2", "pyzmq==26.4.0", "questionary==2.1.0", "randomgen==2.1.1", "referencing==0.36.2", "rpds-py==0.24.0", "scikit-learn==1.6.1", "scipy==1.15.2", "shiny==1.4.0", "six==1.17.0", "sniffio==1.3.1", "soupsieve==2.6", "stack-data==0.6.3", "starlette==0.46.2", "threadpoolctl==3.6.0", "tinycss2==1.4.0", "tomli==2.2.1", "tornado==6.4.2", "traitlets==5.14.3", "typing-extensions==4.13.2", "uc-micro-py==1.0.3", "uvicorn==0.34.1", "watchfiles==1.0.5", "wcwidth==0.2.13", "webencodings==0.5.1", "websockets==15.0.1", "wrapt==1.17.2"]
