[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dp_creator_ii"
authors = [{name = "Chuck McCallum", email = "mccallucc@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "shiny",
    "matplotlib",
    "opendp[polars]",
    "jupytext",
    "jupyter-client",
    "nbconvert",
    "ipykernel",
]

[project.scripts]
dp-creator-ii = "dp_creator_ii:main"

[project.urls]
Home = "https://github.com/opendp/dp-creator-ii"
